version: '3'
volumes:
    data:
services:
    db:
        container_name: db
        image: postgres:9.6
        environment:
            POSTGRES_USER: django
            POSTRES_PASSWORD: django
        volumes:
            - data:/var/lib/postgresql/data
