# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=3)),
                ('price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('market_value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('qty', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='clients.Client')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='securities.Security')),
            ],
        ),
    ]
