# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_security', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('security_id', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('security_type', models.CharField(choices=[('AE', 'ASXEquity')], default='AE', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Securities',
            },
        ),
        migrations.AlterUniqueTogether(
            name='security',
            unique_together=set([('security_type', 'code'), ('security_type', 'security_id')]),
        ),
        migrations.AddField(
            model_name='price',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='securities.Security'),
        ),
    ]
