SECURITY_TRADE_TYPE_OPTION_BUY = 'B'
SECURITY_TRADE_TYPE_OPTION_SELL = 'S'

SECURITY_TRADE_TYPE_OPTIONS = (
    (SECURITY_TRADE_TYPE_OPTION_BUY, 'Buy'),
    (SECURITY_TRADE_TYPE_OPTION_SELL,  'Sell')
)

SECURITY_TRADE_TYPE_OPTIONS_VALS = [e[0] for e in SECURITY_TRADE_TYPE_OPTIONS]
