# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('advisor_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Licensee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('licensee_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='advisor',
            name='licensee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='advisors.Licensee'),
        ),
        migrations.AlterUniqueTogether(
            name='advisor',
            unique_together=set([('advisor_id', 'licensee')]),
        ),
    ]
